import { Header } from "@/components/header";
import Flag from "@/components/icons/flag";
import { Phone } from "lucide-react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased [--header-height:108px] [font-family:var(--font-geist-sans)]`}
      >
        <Header />
        {children}
        <footer className="bg-background border-t">
          {/* CTA Section */}
          <div className="bg-chart-3 py-8 lg:py-12">
            <div className="container mx-auto px-4">
              <div className="flex flex-col items-center justify-center text-center">
                <h2 className="text-3xl font-bold text-background mb-3 lg:mb-4">Ready to Get Started?</h2>
                <p className="text-lg text-background/90 mb-6 lg:mb-8 max-w-2xl">
                  Whether you're moving across the province or across borders, we're here to make your move smooth and stress-free.
                </p>
                <div className="flex flex-col sm:flex-row gap-4">
                  <Link
                    href="#quote"
                    className="inline-flex h-12 items-center justify-center rounded-md bg-background px-8 text-base font-medium text-chart-3 shadow transition-colors hover:bg-background/90"
                  >
                    Get a Quote
                  </Link>
                  <Link
                    href={`tel:${process.env.NEXT_PUBLIC_CONTACT_NUMBER}`}
                    className="inline-flex h-12 items-center justify-center rounded-md border border-background bg-transparent px-8 text-base font-medium text-background shadow-sm transition-colors hover:bg-background/10"
                  >
                    <Phone className="mr-2 h-5 w-5" />
                    {process.env.NEXT_PUBLIC_CONTACT_NUMBER}
                  </Link>
                </div>
              </div>
            </div>
          </div>

          {/* Footer Content - Reduced padding */}
          <div className="container mx-auto px-4 pt-8 lg:pt-12 pb-6 lg:pb-8">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-8 lg:gap-12">
              <div className="space-y-4 md:col-span-2">
                <h3 className="text-lg font-semibold">{process.env.NEXT_PUBLIC_COMPANY_NAME}</h3>
                <p className="text-muted-foreground">Professional moving services across Canada and beyond. Licensed, insured, and committed to excellence.</p>
                <div className="flex items-center gap-2 pt-2">
                  <span className="text-muted-foreground text-sm">Operated by</span>
                  <a
                    target="_blank"
                    href={process.env.NEXT_PUBLIC_TENANT_URL}
                    className="text-foreground text-lg font-semibold flex items-center hover:text-foreground/80"
                  >
                    TNM <Flag className="h-5 w-5 ml-1" />
                  </a>
                </div>
              </div>

              <div className="space-y-4">
                <h3 className="font-semibold">Contact</h3>
                <div className="space-y-2 text-muted-foreground">
                  <p>{process.env.NEXT_PUBLIC_LOCATION}</p>
                  <p>
                    <a className="underline hover:text-foreground" href={`tel:${process.env.NEXT_PUBLIC_CONTACT_NUMBER}`}>{process.env.NEXT_PUBLIC_CONTACT_NUMBER}</a>
                  </p>
                  <p>
                    <a className="underline hover:text-foreground" href={`mailto:${process.env.NEXT_PUBLIC_CONTACT_EMAIL}`}>{process.env.NEXT_PUBLIC_CONTACT_EMAIL}</a>
                  </p>
                </div>
              </div>

              <div className="space-y-4">
                <h3 className="font-semibold">Quick Links</h3>
                <div className="space-y-2">
                  <Link href="#quote" className="block text-muted-foreground hover:text-foreground">Get a Quote</Link>
                  <Link href="/about-us" className="block text-muted-foreground hover:text-foreground">About Us</Link>
                  <a href={process.env.NEXT_PUBLIC_GOOGLE_REVIEWS_URL} target="_blank" rel="noopener noreferrer" className="block text-muted-foreground hover:text-foreground">Reviews</a>
                </div>
              </div>
            </div>

            <div className="border-t mt-12 pt-8 text-center text-muted-foreground">
              <p>© {new Date().getFullYear()} {process.env.NEXT_PUBLIC_COMPANY_NAME}. All rights reserved.</p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
